import Header from "../../component/head/Header";
import "./globals.css";
import '@/styles/header/nav.css'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>
        <header>
          <Header />
        </header>

        <main>{children}</main>
      </body>
    </html>
  );
}
